author: Matthew Miner
baseurl: "" # Subpath, e.g. /blog/
description: Software Engineer and Game Developer
permalink: /:year/:month/:day/:title
title: Matthew Miner
url: "https://matthewminer.com" # Base hostname and protocol

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed

# Build settings
compress_html:
  clippings: all
  comments: ["/*! ", " */"]
sass:
  style: compressed
